---
title: "p8105_hw1_mjn2142"
author: "Matthew Neky"
date: "9/21/2021"
output: github_document
---

###Problem 1

```{r setup}
library(tidyverse)
```

##Data Frame

```{r}
p1_df = tibble(
    ran_samp = rnorm(10),
    vec_logical = ran_samp > 0,
    vec_char = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J"),
    vec_fac = factor(c("yellow", "blue", "red", "yellow", "blue", "red", "yellow", "blue", "red", "yellow"))
)

knitr::kable(p1_df, format = "html")

##Means of Data Frame Variables

mean(p1_df %>% pull(ran_samp))

mean(p1_df %>% pull(vec_logical))

mean(p1_df %>% pull(vec_char))

mean(p1_df %>% pull(vec_fac))
```

#Mean can only be taken for ran_samp and vec_logical because they have numeric values associated with them, not vec_char or vec_fac which only have characters associated with them.

###Problem 2

```{r}
data("penguins", package = "palmerpenguins")

summary(penguins)
nrow(penguins)
ncol(penguins)

mean(penguins$flipper_length_mm, na.rm = TRUE)
```

##Scatterplot

```{r, message = FALSE, warning = FALSE}
peng_plot = ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
ggsave("peng_plot.png")
knitr::fig_chunk('peng_plot', 'png')
```


